
services:

    mysql:
        image: mysql:8.2
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8086:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

    laravel:
        image: laravel:latest
        restart: always
        ports:
            - "8000:8000"
        depends_on:
          - mysql
          - vuejs
        networks:
            - app-network
        volumes:
          - .:/laravel

    vuejs:
        image: vue:latest
        restart: always
        ports:
            - "8080:8080"
        networks:
            - app-network


volumes:
  db_data:


networks:
    app-network:
        driver: bridge
